# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Gatsby
      working-directory: gatsby-site
      run: | 
        echo "module.exports.mongodbPassword = '${{ secrets.MONGODB_PASSWORD }}';" > passwords.js
        npm install
        npm run build

    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.DEPLOY_HOST }}
        ftp_username: ${{ secrets.DEPLOY_ACCOUNT }}
        ftp_password: ${{ secrets.DEPLOY_PASSWORD }}
        local_source_dir: "gatsby-site/public"
        dist_target_dir: ${{ secrets.DEPLOY_DIR}}
        delete: "true"
        only_newer: "true"
        ignore_time: "true"

